### PR TITLE
Apply toJSON if exists

### PR DESCRIPTION
**Pull request by cemremengu**
Attempts #118 

Node v8.11.3
```
FJS creation x 5,338 ops/sec ±4.96% (83 runs sampled)
JSON.stringify array x 3,254 ops/sec ±1.73% (94 runs sampled)
fast-json-stringify array x 4,697 ops/sec ±1.30% (95 runs sampled)
fast-json-stringify-uglified array x 4,446 ops/sec ±1.37% (95 runs sampled)
JSON.stringify long string x 10,435 ops/sec ±0.39% (97 runs sampled)
fast-json-stringify long string x 10,417 ops/sec ±0.59% (91 runs sampled)
fast-json-stringify-uglified long string x 10,401 ops/sec ±0.50% (95 runs sampled)
JSON.stringify short string x 4,313,552 ops/sec ±4.12% (86 runs sampled)
fast-json-stringify short string x 9,798,598 ops/sec ±0.94% (94 runs sampled)
fast-json-stringify-uglified short string x 9,851,120 ops/sec ±0.79% (93 runs sampled)
JSON.stringify obj x 1,804,050 ops/sec ±1.18% (96 runs sampled)
fast-json-stringify obj x 4,279,013 ops/sec ±1.63% (92 runs sampled)
fast-json-stringify-uglified obj x 4,198,298 ops/sec ±0.86% (96 runs sampled)
```

### CODE REVIEW

**Comment by sarneeh** [comment]
This approach is wrong. You should not call `JSON.stringify()` on your `toJSON` method. Quoting MDN: `If the value has a toJSON() method, it's responsible to define what data will be serialized.`. `toJSON` is for mapping your object to some other structure (for external use), not for serialization.

**Comment by cemremengu** [comment]
@sarneeh Yes, you are right I was actually just trying to mimic the output of `fast-stringify` instead of a correct implementation

**Comment by lmammino** [comment]
I have seen the `toJSON` being used also to evaluate lazy loaded properties (most often in the context of ORM systemsl, to make sure that the serialized items would contain all the attributes. Even in this case the `toJSON` would return a plain JS object with the fields that should be serialized and not a serialized string.

**Comment by cemremengu** [comment]
@lmammino Yeah, looks like I messed up. Didnt know that the spec/usage is that strict on how you use it.

Thanks for the info I really appreciate it! :smile:

**Pull request closed without merging**
