### PR TITLE
fix: check all types for toJSON function

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

toJSON function can return any type as a result. Not it's working only if object has toJSON method that returns another object.

There is a problem with the Date type. It has toJSON function by default, and it's not clear how to handle this case.

### CODE REVIEW

**Comment by mcollina** [comment]
Does this causes any perf regression?

**Comment by ivan-tymoshenko** [comment]
Снимок экрана 2022-05-25 в 19 16 05

**Comment by ivan-tymoshenko** [comment]
It's an interesting example https://github.com/fastify/fast-json-stringify/blob/03f8714fc2412c3e46cb7bbb947e316cad0681bc/test/date.test.js#L129.

`moment` is an object. It's not a `Date` type . It has toJSON method. Should we call it?

**Comment by mcollina** [comment]
The test is correct.

**Comment by mcollina** [comment]
Is this still in the works? What's meeting?

**Comment by ivan-tymoshenko** [comment]
If someone would like to help with this issue, I would appreciate it. Working on another problem right now.

**Comment by bmenant** [comment]
@ivan-tymoshenko Did you see https://github.com/fastify/fast-json-stringify/pull/414 ?
I tried to tackle this as well, started with pretty much the same changes you did so far, and went even further way, before eventually giving up:

> Turns out this is far tougher than expected. Notably, the logic laid out toward the nested() function requires too many conditions and exceptions, preventing easy and safe (and fast?) behavior addition such as this one.

IMHO, a thorough refactoring is needed in and around the `nested()` function before. But, to be honest, it’s not easy task to grasp the whole logic of the code builder. It has been written to output optimized code from the ground up for a reason. I personally lack the skills and the time to tackle this.

After all, AFAIK none of the _fast_ json stringify lib I tried out there supports such toJSON feature.

Anyway, I’d be glad to discuss the topic and give a hand if you deem so useful.

**Pull request closed without merging**
