### PR TITLE
Infer type schema

### PR DESCRIPTION
**Pull request by DanieleFedeli**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This PR is linked to #509 and aims to propagate schema type to the final function

[This](https://github.com/fastify/fast-json-stringify/issues/509#issuecomment-1228626784) comment showed the outcome.

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
I am not really convinced to add `json-schema-to-ts` as dependency for this project.

However, I do agree we should provide some generic params for the input validation.

**Comment by Liam-Tait** [comment]
@climba03003 I agree, I don't think this should be tied to a single json schema package 

My argument for having a simple generic is here
https://github.com/fastify/fast-json-stringify/issues/509#issuecomment-1229181217

**Comment by DanieleFedeli** [comment]
> @climba03003 I agree. The implementation should work across json schema libraries.
> 
> I detailed why a generic only extending object is better for cross library support here. [#509 (comment)](https://github.com/fastify/fast-json-stringify/issues/509#issuecomment-1229181217)
> 
> Putting the onus on the user to provide the correct type is a good trade off for flexibility.

So if everyone is ok I can update the PR

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Liam-Tait** [comment]
Nice. Thanks @DanieleFedeli I appreciate you

**Review by climba03003 — APPROVED** [review]

**Pull request merged**
