### PR TITLE
fix multi default

### LINKED ISSUE #251: Stringify fails with multiple defaults
## 🐛 Bug Report

Stringifying fails when using multiple defaults + required.  This isn't the case when using AJV directly.  
You can run it here: https://repl.it/@gabemeola/fast-json-stringify-default-issue  

Removing `required` passes but isn't the intended schema.  
Removing all but one `default` and `required` does pass as intended. 
e.g.  
```
const schema = {
  type: 'object',
  properties: {
    name: {
      default: 'Person',
      type: 'string',
    },
  },
  required: [
    'name',
  ]
}

```

## To Reproduce

```js
const fastJson = require('fast-json-stringify')
const Ajv =  require('ajv')

const ajv = new Ajv({ useDefaults: true });

const schema = {
  type: 'object',
  properties: {
    name: {
      default: 'Person',
      type: 'string',
    },
    dev: {
      type: 'boolean',
      default: false,
    }
  },
  required: [
    'name',
    'dev'
  ]
}

const validate = ajv.compile(schema);
const str = fastJson(schema)

console.log("AJV Passed:", validate({}))
console.log(str({})) // Error: "name" is required!
```

## Expected behavior

```js
{ "name": "Person", "dev": false }
```

## Your Environment

- *node version*: 12
- *fastify version*: 2.2.3

### PR DESCRIPTION
**Pull request by Eomm**
Fixes #251 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks! CI is failing https://github.com/fastify/fast-json-stringify/pull/257/checks?check_run_id=1095141512#step:5:723.

**Comment by Eomm** [comment]
Coding on the browser is hard

**Review by zekth — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Review by fox1t — APPROVED** [review]
LGTM!

**Review by L2jLiga — APPROVED** [review]
lgtm 👍

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
