### PR TITLE
Test cases for #413 and #417

### PR DESCRIPTION
**Pull request by samchon**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Test would be failed because it's a PR reproducing some bugs

### CODE REVIEW

**Comment by mcollina** [comment]
Awesome!

**Comment by mcollina** [comment]
Would you also be pushing a fix?

**Comment by samchon** [comment]
No bug fix, I do not know how to

**Comment by samchon** [comment]
@mcollina Found how to fix the #417 bug, wait for a while.

**Comment by mcollina** [comment]
I won't have time to dig deep into this problem for a while. I'll be happy to review if you can find a fix.

**Comment by samchon** [comment]
It seems bug from the `ajv` TT.

**Comment by samchon** [comment]
@mcollina 

Succeeded to fix the #417 bug. The `ajv` can't `$refer` itself, therefore `$recursiveRef` must be used.

However, I couldn't fix the #413 bug. Can you accept this PR and publish new version with your manual editing?

**Comment by mcollina** [comment]
What do you mean manual editing?

**Comment by samchon** [comment]
@mcollina Erase unit test for #413 and revive it when you ready

**Comment by samchon** [comment]
Found another bug, wait for a while please.

**Pull request closed without merging**
