### PR TITLE
chore(perf): asStringSmall slower than JSON.stringify

### PR DESCRIPTION
**Pull request by cesco69**
`asStringSmall`  seem slower than `JSON.stringify`

[online benchmark](https://perf.link/#eyJpZCI6ImVueW1ieXRpdnY2IiwidGl0bGUiOiJhc1N0cmluZ1NtYWxsIHZzIEpTT04uc3RyaW5naWZ5IiwiYmVmb3JlIjoiZnVuY3Rpb24gYXNTdHJpbmdTbWFsbChzdHIpIHtcbiAgICBjb25zdCBsZW4gPSBzdHIubGVuZ3RoXG4gICAgbGV0IHJlc3VsdCA9ICcnXG4gICAgbGV0IGxhc3QgPSAtMVxuICAgIGxldCBwb2ludCA9IDI1NVxuXG4gICAgLy8gZXNsaW50LWRpc2FibGUtbmV4dC1saW5lXG4gICAgZm9yICh2YXIgaSA9IDA7IGkgPCBsZW47IGkrKykge1xuICAgICAgcG9pbnQgPSBzdHIuY2hhckNvZGVBdChpKVxuICAgICAgaWYgKHBvaW50IDwgMzIgfHwgKHBvaW50ID49IDB4RDgwMCAmJiBwb2ludCA8PSAweERGRkYpKSB7XG4gICAgICAgIC8vIFRoZSBjdXJyZW50IGNoYXJhY3RlciBpcyBub24tcHJpbnRhYmxlIGNoYXJhY3RlcnMgb3IgYSBzdXJyb2dhdGUuXG4gICAgICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShzdHIpXG4gICAgICB9XG4gICAgICBpZiAoXG4gICAgICAgIHBvaW50ID09PSAweDIyIHx8IC8vICdcIidcbiAgICAgICAgcG9pbnQgPT09IDB4NWMgLy8gJ1xcJ1xuICAgICAgKSB7XG4gICAgICAgIGxhc3QgPT09IC0xICYmIChsYXN0ID0gMClcbiAgICAgICAgcmVzdWx0ICs9IHN0ci5zbGljZShsYXN0LCBpKSArICdcXFxcJ1xuICAgICAgICBsYXN0ID0gaVxuICAgICAgfVxuICAgIH1cblxuICAgIHJldHVybiAobGFzdCA9PT0gLTEgJiYgKCdcIicgKyBzdHIgKyAnXCInKSkgfHwgKCdcIicgKyByZXN1bHQgKyBzdHIuc2xpY2UobGFzdCkgKyAnXCInKVxuICB9XG5jb25zdCBTVFJfMSAgPSAnQSdcbmNvbnN0IFNUUl8xMCA9IFNUUl8xIC5yZXBlYXQoMTApXG5jb25zdCBTVFJfMjAgPSBTVFJfMSAucmVwZWF0KDIwKVxuY29uc3QgU1RSXzMwID0gU1RSXzEgLnJlcGVhdCgzMClcbmNvbnN0IFNUUl80MCA9IFNUUl8xIC5yZXBlYXQoNDApIiwidGVzdHMiOlt7Im5hbWUiOiJhc1N0cmluZ1NtYWxsKFNUUl8xKSIsImNvZGUiOiJhc1N0cmluZ1NtYWxsKFNUUl8xKSIsInJ1bnMiOlsxMDAwLDMxMjAwMCw0ODAwMCwyMTUwMDAsMzEyMDAwLDEwMDAsMzEyMDAwLDY3MzAwMCwxNzEwMDAsMzEyMDAwLDEwMDAsNTIwMDAsMjQwMDAwLDE2ODAwMCwxMDAwLDUyODAwMCw2MDAwLDI4MzAwMCw0NzUwMDAsMzYxMDAwLDIwMDAwMCw5MDYwMDAsMTUzMDAwLDEwMDAsMTAwMCw1NjAwMCw3MjQwMDAsNzg2MDAwLDIzNjAwMCwxMDAwLDMxMjAwMCwzMTIwMDAsMTAwMCwzMTIwMDAsMTE4MDAwLDMxMjAwMCw3MDIwMDAsMjIwMDAwLDY1MDAwLDI3MTAwMCwzODQwMDAsMzE1MDAwLDE3MjAwMCwxMDAwLDMxMzAwMCwzNjYwMDAsNjg2MDAwLDkxMDAwLDMxMjAwMCwxMDUwMDAsMTcwMDAsMTQ0MDAwLDMxMjAwMCwxMDAwLDE3MDAwLDU2MjAwMCwxMDAwLDEwMDAsMzEyMDAwLDEyNTAwMCwzNTAwMCwzMTIwMDAsMzg3MDAwLDQ4MzAwMCwxMDAwLDE1OTAwMCwyMTAwMCwxMDAwLDYwMDAsMzEyMDAwLDE3NDAwMCwxMDAwLDMxMjAwMCwxMDAwLDk2MDAwLDI3MDAwLDIwOTAwMCwyNTcwMDAsMzEyMDAwLDE3MDAwMCwxMDAwLDUwMDAsMTUzMDAwLDMxMTAwMCwxNTkwMDAsMzEyMDAwLDMxMjAwMCwzMTIwMDAsMjI3MDAwLDQ4NjAwMCwzMTIwMDAsMzEyMDAwLDEwMDAsMzEyMDAwLDc1MDAwLDEwMDAsMjI0MDAwLDUyOTAwMCwxNDAwMDAsMjY1MDAwXSwib3BzIjoyMjEyMzB9LHsibmFtZSI6IkpTT04uc3RyaW5naWZ5KFNUUl8xKSIsImNvZGUiOiJKU09OLnN0cmluZ2lmeShTVFJfMSkiLCJydW5zIjpbNTk3MDAwLDY2MjAwMCw5NDAwMDAsMzY1MDAwLDE0NDAwMCw4NTkwMDAsMzMzMDAwLDc3MDAwMCw0MDcwMDAsNjkyMDAwLDQ4MjAwMCw1ODYwMDAsNjU1MDAwLDEzOTkwMDAsNDk2MDAwLDEzOTkwMDAsNTQ3MDAwLDg1NjAwMCwyMDY4MDAwLDUzMjAwMCw2NzMwMDAsMTM5OTAwMCwyNTAwMDAsNTQzMDAwLDMxNTAwMCwyMTMwMDAsOTUyMDAwLDU4MzAwMCw5OTEwMDAsMTg1MDAwLDYxMDAwMCw4MDkwMDAsNTE2MDAwLDUwMDAwLDQ1NTAwMCwzMDAwLDMyNTAwMCw3ODkwMDAsMTQ4MDAwLDU2NzAwMCwzOTcwMDAsNjIzMDAwLDE0ODAwMCwyNzQwMDAsNTk2MDAwLDc1NDAwMCwxOTgwMDAwLDEzOTcwMDAsMTEyODAwMCw2MDEwMDAsNTQ1MDAwLDQzOTAwMCwzMTcwMDAsMTkyMDAwLDc0NjAwMCwxMTQyMDAwLDMyMTAwMCwxNjUwMDAsMzAxMDAwLDM5NzAwMCwyNTAwMDAsNjE5MDAwLDI5NzAwMCw1NTAwMCwyNjUwMDAsMzIwMDAwLDEwNjYwMDAsMzUxMDAwLDE3MzAwMCwxMzk5MDAwLDExNjgwMDAsNDM4MDAwLDQ3MTAwMCwxOTAwMCw5MjEwMDAsMTgwMDAsNDI1MDAwLDY2MjAwMCw1MDYwMDAsODMwMDAsNDg4MDAwLDg3NTAwMCw1MDYwMDAsMTc3NjAwMCw1NTAwMCwxMTU3MDAwLDI1NzAwMCw4MDUwMDAsNTgwMDAwLDI4MzAwMCwxMzk5MDAwLDczODAwMCw4MjAwMDAsMTM5OTAwMCwxMDczMDAwLDEyMTUwMDAsMTU0NDAwMCw5NTIwMDAsMTQ1MDAwLDcxMDAwMF0sIm9wcyI6NjM5MTEwfSx7Im5hbWUiOiJhc1N0cmluZ1NtYWxsKFNUUl8xMCkiLCJjb2RlIjoiYXNTdHJpbmdTbWFsbChTVFJfMTApIiwicnVucyI6WzEwMDAsMTAwMCwxNjAwMCw3MTAwMCwyMjAwMCw1MDAwLDIwMDAsNzgwMDAsNjgwMDAsNTMwMDAsMTAwMCw1MzAwMCwxMDAwLDk5MDAwLDI0NDAwMCw3MTAwMCwyNTUwMDAsMTAwMCwxMDAwLDIwMDAsNzEwMDAsNDMwMDAsMTAwMCwyMzEwMDAsOTkwMDAsNDc3MDAwLDUyNzAwMCw0ODAwMCwyMDAwLDEwNTAwMCwzOTAwMCw3MTAwMCwxMDAwLDExMjAwMCw3MTAwMCw5MTAwMCw3MTAwMCw1MzAwMCw3MTAwMCwxMTAwMCwxMDAwLDcxMDAwLDcxMDAwLDE2MDAwLDcxMDAwLDcxMDAwLDcxMDAwLDcxMDAwLDEwMDAsMjAyMDAwLDEwMDAsMTQwMDAsMTAwMCw1MDAwMCwxMDAwLDcxMDAwLDcxMDAwLDIwMDAsNzEwMDAsMTQwMDAwLDEzMDAwLDcxMDAwLDQwMDAwLDEwMDAsNzEwMDAsMTAwMCwyNjAwMCwxMDAwLDMxNTAwMCw4ODAwMCwyMDUwMDAsNzEwMDAsNDkwMDAsMjE2MDAwLDMyMTAwMCw3MDAwMCw0MDAwLDY4MDAwLDcxMDAwLDIyODAwMCwxMDAwLDEwMDAsNzEwMDAsMTMwMDAsNzAwMDAsMTQyMDAwLDEwMDAsMTAwMCw0MDAwMCwxMzcwMDAsODQwMDAsNzEwMDAsNzEwMDAsMTE1MDAwLDcxMDAwLDIxMDAwLDEwMDAsNzEwMDAsMTEwMDAsODIwMDBdLCJvcHMiOjczMTMwfSx7Im5hbWUiOiJKU09OLnN0cmluZ2lmeShTVFJfMTApIiwiY29kZSI6IkpTT04uc3RyaW5naWZ5KFNUUl8xMCkiLCJydW5zIjpbMzYwMDAwLDUyNjAwMCwyMzgwMDAsNzI0MDAwLDM1NTAwMCw0MjAwMDAsNzg4MDAwLDEwMDkwMDAsNDUyMDAwLDQyMjAwMCwyNTQwMDAsOTYwMDAsNzAwMDAsMTAxMzAwMCwzOTYwMDAsMzczMDAwLDEzOTkwMDAsMTMxMDAwLDExODcwMDAsNjI3MDAwLDg1OTAwMCwzMDAwMCw5MTAwMDAsMTAzMDAwLDMzOTAwMCwxMjE5MDAwLDMyOTAwMCw4NzIwMDAsNTMwMDAwLDg2OTAwMCwxNzkwMDAsMTM5OTAwMCw1MjAwMCwzOTQwMDAsODgwMDAwLDQ3NTAwMCw1NTkwMDAsNjQ1MDAwLDIwODAwMCw0MjIwMDAsOTg3MDAwLDg4OTAwMCwyNDYwMDAsOTc3MDAwLDE0NzQwMDAsNzc3MDAwLDkxNDAwMCwxMTc1MDAwLDgzNjAwMCw1MDEwMDAsMTM5OTAwMCwyNTkwMDAsNjY4MDAwLDU0MDAwMCwyMDAwLDQ5NzAwMCwxNDkwMDAsMjQ1MDAwLDkzOTAwMCwxMzQwMDAsMzE0MDAwLDk5NjAwMCw4NTQwMDAsODEwMDAsNzY5MDAwLDM5MjAwMCw0NzYwMDAsMTM5OTAwMCwxMjQ3MDAwLDEzMDAwMDAsMTM5OTAwMCw5NDEwMDAsNDkyMDAwLDI5MDAwLDUzNzAwMCw3NjQwMDAsNjg4MDAwLDEzMzYwMDAsMzIzMDAwLDk0MDAwMCw1MzQwMDAsMzU3MDAwLDE3MDAwLDU1ODAwMCwyMjAwMCwzNDMwMDAsNzYwMDAwLDI0MjAwMCwzODAwMDAsMTI0MDAwLDQ2MjAwMCw4MDIwMDAsMTk1MDAwLDEwMDAwLDI0NjIwMDAsNjgxMDAwLDEwOTAwMCw1MzMwMDAsMTcwMDAsMTk2MDAwXSwib3BzIjo1OTgwMjB9LHsibmFtZSI6ImFzU3RyaW5nU21hbGwoU1RSXzIwKSIsImNvZGUiOiJhc1N0cmluZ1NtYWxsKFNUUl8yMCkiLCJydW5zIjpbMTEwMDAsMzkwMDAsMzkwMDAsMzkwMDAsMTc3MDAwLDIyMDAwLDEyMzAwMCwyNjAwMCw2MDAwLDMzMDAwLDEwMDAsMTkwMDAsMTAwMCwxMDAwLDEwMDAsMTAwMCwzOTAwMCwxMDAwLDE4MzAwMCwxMDAwLDM5MDAwLDEwMDAsMTAwMCwzOTAwMCwzOTAwMCwxOTQwMDAsMzcwMDAsMjExMDAwLDEwMDAsMTMwMDAsMzkwMDAsMzkwMDAsMTAwMCwyMTAwMCwzOTAwMCwxMDAwLDE2MzAwMCwyMzAwMCwzOTAwMCw1MzAwMCwzOTAwMCw3OTAwMCw1MTAwMCwyMzAwMCwxMDAwMDAsMTAwMCw1NjAwMCwzOTAwMCwyMDAwLDIxMDAwLDM5MDAwLDgwMDAsMTA5MDAwLDEwMDAsMTAwMCwyODAwMCwxMDAwLDEwMDAsMCwzOTAwMCwzOTAwMCwzOTAwMCwxMzAwMCwxODAwMCwzOTAwMCwxMDAwLDM5MDAwLDIxNzAwMCwxNjcwMDAsMjEwMDAsMzkwMDAsNDAwMCwzOTAwMCwzOTAwMCwxMDAwLDQwMDAsMzIwMDAsMzgwMDAsNDEwMDAsMzkwMDAsNTMwMDAsMTAwMCw2MDAwLDEwMDAsMzkwMDAsMzUwMDAsMjkwMDAsNDIwMDAsMjcwMDAsMTAwMCwzNTAwMCw1NTAwMCwxNTQwMDAsMzkwMDAsMzkwMDAsMjkwMDAsMTAwMCwxMDAwLDM5MDAwLDEwMDBdLCJvcHMiOjM4OTAwfSx7Im5hbWUiOiJKU09OLnN0cmluZ2lmeShTVFJfMjApIiwiY29kZSI6IkpTT04uc3RyaW5naWZ5KFNUUl8yMCkiLCJydW5zIjpbMzc0MDAwLDQ4NTAwMCwzNDcwMDAsMjM5MDAwLDQxMzAwMCwyNDIwMDAsOTk5MDAwLDYyMzAwMCw1MzIwMDAsNDUyMDAwLDEwNDUwMDAsMTc4MDAwLDEzOTkwMDAsMTY0MjAwMCw4MDYwMDAsNTMwMDAsNjcyMDAwLDU3MjAwMCwzMzEwMDAsNzcxMDAwLDU3MDAwLDI5NTAwMCwzMTAwMCwxMzUwMDAwLDM3MzAwMCw5MDAwMCwxOTAwMCwzMDEwMDAsMTQ2MDAwLDc4MzAwMCwyMTEwMDAsMTY1MDAwLDc0MDAwLDQ4NzAwMCwwLDI2ODAwMCw0NzIwMDAsMTA2MTAwMCwxMDEyMDAwLDM2MDAwMCwyMDMwMDAsNDUxMDAwLDM4MzAwMCw0NzgwMDAsNjgyMDAwLDQ4NzAwMCwzMzgwMDAsMTM5OTAwMCwzMTcwMDAsMTM5OTAwMCw4NjQwMDAsNzA2MDAwLDEzOTkwMDAsOTAyMDAwLDEwNzYwMDAsMzk2MDAwLDk4ODAwMCwxMDc2MDAwLDUyNTAwMCw3ODUwMDAsMTQ3MDAwLDg5MDAwLDEzOTAwMCwyMjUwMDAsMTM5OTAwMCwzMjgwMDAsNzkwMDAsMTI2MzAwMCwxMzk5MDAwLDE0MTMwMDAsODYwMDAwLDY1MjAwMCwzMTIwMDAsOTU1MDAwLDQ3OTAwMCwxNzIwMDAsNDcyMDAwLDY5NDAwMCw1ODMwMDAsMTM5OTAwMCwxMTgwMDAsOTczMDAwLDIzNTAwMCw4MzAwMDAsMTk2MDAwLDk5OTAwMCwzNjEwMDAsNDE0MDAwLDExNTEwMDAsOTEwMDAsODQ4MDAwLDExMTQwMDAsMjM5MDAwLDQzMDAwMCwyNzkwMDAsMTA3MDAwMCw0MDgwMDAsOTE0MDAwLDcxNTAwMCw2MjAwMDBdLCJvcHMiOjU5NjQ4MH0seyJuYW1lIjoiYXNTdHJpbmdTbWFsbChTVFJfMzApIiwiY29kZSI6ImFzU3RyaW5nU21hbGwoU1RSXzMwKSIsInJ1bnMiOlsxMDAwLDEwMDAsMTAwMDAsNzEwMDAsMjcwMDAsMTAwMCwxMDAwLDkxMDAwLDI3MDAwLDI3MDAwLDEwMDAsMjAwMDAsMjcwMDAsMjcwMDAsMTAwMCwyNzAwMCw1OTAwMCwyNzAwMCwyNzAwMCwyNzAwMCwyNzAwMCw5MDAwLDEwMDAsMjcwMDAsMTAwMCwzMTAwMCw3MDAwLDE4MDAwLDI3MDAwLDIwMDAsMjcwMDAsNTUwMDAsODcwMDAsMjcwMDAsMjcwMDAsMzcwMDAsNTAwMDAsMTcwMDAsMjcwMDAsMTAwMCwyNzAwMCwxMDAwLDI3MDAwLDQxMDAwLDI3MDAwLDE1MDAwLDExMjAwMCwxMDAwLDEzOTAwMCwyNzAwMCwyNzAwMCwyNzAwMCwxMjEwMDAsODQwMDAsMTAwMCwyNDAwMCwyNzAwMCwyNTAwMCwyMTAwMCwyNzAwMCwyMDAwMCwyNzAwMCwxMTIwMDAsMjcwMDAsMTcwMDAsMjAwMCwzMjAwMCwxMDAwLDIwODAwMCwyNzAwMCwyMDAwLDI3MDAwLDEwMDAsMTAwMCwyNzAwMCwxMDAwLDIwMDAwLDEwMDAsNTAwMCwyMzAwMCwyNzAwMCwyNzAwMCwyNzAwMCw4OTAwMCwyNzAwMCwyNzAwMCwzNzAwMCwyNzAwMCw0MDAwLDEwMDAsMTAwMCwxMDAwLDI3MDAwLDcwMDAsMTY0MDAwLDI3MDAwLDY0MDAwLDEwMDAsMjMwMDAsMTAwMF0sIm9wcyI6Mjk5NjB9LHsibmFtZSI6IkpTT04uc3RyaW5naWZ5KFNUUl8zMCkiLCJjb2RlIjoiSlNPTi5zdHJpbmdpZnkoU1RSXzMwKSIsInJ1bnMiOls0ODAwMCw1MjAwMCw0NTUwMDAsMTQwMDAsMTAwMCwzMDAwLDE1NjAwMCwyMzUwMDAsNjc0MDAwLDQ1MDAwLDYzNzAwMCwxMTMwMDAsMTMxMDAwLDg1NjAwMCw3MDAwLDQ0MDAwMCwxMjE0MDAwLDIwODAwMCw1NzAwMCwxMTUwMDAsNjcwMDAsODAwMCw4OTYwMDAsNDAwMCw4NDAwMCw0NDAwMDAsNDQ5MDAwLDY1MjAwMCw4NTYwMDAsMjk5MDAwLDE0OTAwMCw3MTQwMDAsOTYwMDAsMzg1MDAwLDYyNTAwMCw2MjcwMDAsMjA0MDAwLDI0MDAwLDEwMzAwMCw2MTQwMDAsMjQwMDAwLDEwOTAwMCw1NjAwMCw4MDUwMDAsMTYzMDAwLDYyNTAwMCwxMjk3MDAwLDk3ODAwMCw1MTkwMDAsMTAwMCwyODkwMDAsMzU2MDAwLDEwMDcwMDAsMjI5MDAwLDEwNjAwMDAsNTkzMDAwLDEwNzYwMDAsNDYwMDAsNzMxMDAwLDUzNzAwMCw1NDgwMDAsMTg4MDAwLDM5MTAwMCw1NDUwMDAsMTI1MDAwLDkyMDAwLDUyMDAwLDEyODQwMDAsMTgwMDAwLDcxMDAwMCwxMDk2MDAwLDEwNTUwMDAsNTk5MDAwLDU4MDAwLDE5ODAwMCw0ODcwMDAsNTI5MDAwLDM0MjAwMCw4MTgwMDAsMjI0MDAwLDI2NjAwMCwxMDMwMDAsNDcwMDAwLDE0NzAwMCwzNjkwMDAsMjk5MDAwLDQ0NTAwMCw4NzQwMDAsNTE4MDAwLDE5ODAwMCwxODEwMDAsMjUwMDAwLDc1NDAwMCw5OTgwMDAsOTMxMDAwLDI1MDAwLDU2MTAwMCwzNzUwMDAsMjAwMDAsNTY0MDAwXSwib3BzIjo0MTM0MzB9LHsibmFtZSI6ImFzU3RyaW5nU21hbGwoU1RSXzQwKSIsImNvZGUiOiJhc1N0cmluZ1NtYWxsKFNUUl80MCkiLCJydW5zIjpbMTYwMDAsMTAwMCwyMTAwMCwyMDAwLDIxMDAwLDYwMDAsMTAwMCwxMDAwLDEwMDAsNjAwMCwzMjAwMCwyMTAwMCw2NDAwMCw3MTAwMCw0NDAwMCwxMTAwMCwyMTAwMCwyMTAwMCwyMTAwMCwyNDAwMCwxNjQwMDAsMjEwMDAsMTAwMCwxNjAwMCwyMTAwMCwxMDAwLDcwMDAsMTAwMCw0MTAwMCwyMTAwMCwyNDAwMCwyMTAwMCwyOTAwMCwxMDAwLDE2MDAwLDIxMDAwLDIwMDAsMjYwMDAsNDkwMDAsNDUwMDAsMjcwMDAsMjEwMDAsMTAwMCwyOTAwMCwxMDAwLDE4MDAwLDIxMDAwLDIxMDAwLDIxMDAwLDIyMDAwLDEwMDAsMjAwMDAsNTIwMDAsMjEwMDAsMTAwMCwxMDAwLDIxMDAwLDIxMDAwLDIxMDAwLDEzMDAwLDEwMDAsMjkwMDAsMjEwMDAsNDEwMDAsOTIwMDAsOTAwMCw1MDAwLDM1MDAwLDQwMDAsMzMwMDAsMTMwMDAwLDc1MDAwLDEwMDAsMTAwMCwxMDAwLDIxMDAwLDEwMDAsMjEwMDAsMzgwMDAsMjEwMDAsMTAwMCwxMDAwLDE0MDAwLDIwMDAsMTAwMCwxMDAwLDU4MDAwLDgwMDAsMTAwMCwyMTAwMCwxMDAwLDI4MDAwLDEwMDAsNjAwMCwxMjAwMCwyMTAwMCwyMTAwMCwxOTAwMCwyMTAwMCw3ODAwMF0sIm9wcyI6MjE4NDB9LHsibmFtZSI6IkpTT04uc3RyaW5naWZ5KFNUUl80MCkiLCJjb2RlIjoiSlNPTi5zdHJpbmdpZnkoU1RSXzQwKSIsInJ1bnMiOls4NDAwMCw3NjAwMCw1MjQwMDAsNTI0MDAwLDM5MDAwLDQzNzAwMCwzOTYwMDAsNDEyMDAwLDYzMTAwMCwxMDgwMDAwLDI0NzAwMCwxMzQwMDAsNDQ2MDAwLDExNDAwMCwxMzk5MDAwLDE1NzAwMCw5NzYwMDAsNDIwMDAsMjU4MDAwLDQyMDAwLDE3MDAwLDY3MDAwLDQ2NjAwMCwyODIwMDAsNzgzMDAwLDExMjcwMDAsMTMyMDAwMCwzOTcwMDAsMjcwMDAwLDQyODAwMCwyMjcwMDAsMTAzMDAwLDIxNjAwMCw4MzAwMCw3ODUwMDAsMjI0MDAwLDE5MDAwLDM4MDAwLDg2MDAwLDUyOTAwMCw1MDUwMDAsNTAwMDAwLDEwMDAsMjAwMDAsMTMwMDAwLDEzODAwMDAsODI4MDAwLDEzMDAwMDAsODI1MDAwLDI4NzAwMCw0OTMwMDAsNDg3MDAwLDI3MzAwMCwyMjIwMDAsMzQ0MDAwLDY4NDAwMCwxMzUwMDAsMTcxMDAwLDQ2NDAwMCw0MTQwMDAsNTAwMCw0MjYwMDAsMjEwMDAsMTA3MDAwLDQ5MzAwMCw1MTMwMDAsNDMyMDAwLDU1MzAwMCw4MDIwMDAsNTYwMDAwLDIxNDAwMCw3NTEwMDAsODg0MDAwLDEyNTEwMDAsMTM5OTAwMCw3NzUwMDAsODI2MDAwLDEwNDgwMDAsMTYzMDAwLDE2MzAwMCwyNDEwMDAsMjM3MDAwLDEzOTkwMDAsNDIyMDAwLDcyOTAwMCw1NDAwMDAsMzk1MDAwLDY5NzAwMCw0MTcwMDAsMzE2MDAwLDc4MjAwMCwyOTgwMDAsNDQ1MDAwLDExMzAwMCw0NjQwMDAsMTAwMDAsMTM5OTAwMCwyMjkwMDAsMTMwMDAsNjE3MDAwXSwib3BzIjo0NjA5NzB9XSwidXBkYXRlZCI6IjIwMjQtMDMtMTJUMTQ6MzE6MzAuNjAyWiJ9)

it seems better to use `JSON.stringify` instead of `asStringSmall`

In detail:

```js
// Test cases ...
const STR_1  = 'A'
const STR_10 = STR_1.repeat(10) // 10 chars
const STR_20 = STR_1.repeat(20) // 20 chars
const STR_30 = STR_1.repeat(30) // 30 chars
const STR_40 = STR_1.repeat(40) // 40 chars
```

```
asStringSmall(STR_1)   221,230 ops/s
JSON.stringify(STR_1)  639,110 ops/s

asStringSmall(STR_10)   73,130 ops/s
JSON.stringify(STR_10) 598,020 ops/s

asStringSmall(STR_20)   38,900 ops/s
JSON.stringify(STR_20) 596,480 ops/s

asStringSmall(STR_30)   29,960 ops/s
JSON.stringify(STR_30) 413,430 ops/s

asStringSmall(STR_40)   21,840 ops/s
JSON.stringify(STR_40) 460,970 ops/s
```

JSON.stringify win in all cases.

V8 has optimized version of string escaping [EscapeJSONStringImpl](https://chromium.googlesource.com/chromium/src/base/+/master/json/string_escape.cc#83) and [EscapeSpecialCodePoint](https://chromium.googlesource.com/chromium/src/base/+/master/json/string_escape.cc#37).
A javascript implementation will never beat these in C++

This make `JSON.stringify` always faster on small string. The idea is just skip `JSON.stringify` on medium string without char to escape:

```js
asString (str) {
    // SMALL STRING: JSON.stringify is always faster
    if (str.length < 42) {
      return JSON.stringify(str)
    // MEDIUM STRING: the check of, if string has char to escape, is fast on not big string
    } else if (str.length < 5000 && STR_ESCAPE.test(str) === false) {
      // Only use the regular expression for shorter input. The overhead is otherwise too much.
      return '"' + str + '"'
    // BIG STRING
    } else {
      return JSON.stringify(str)
    }
}
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]
looks good to me, I'd recommend checking the provided V8 code

**Review by mcollina — CHANGES_REQUESTED** [review]
While I would believe the provided benchmark, _our numbers_ shows a different story.

This PR:

```
short string............................................. x 11,870,831 ops/sec ±0.88% (192 runs sampled)
unsafe short string...................................... x 813,671,948 ops/sec ±0.11% (195 runs sampled)
short string with double quote........................... x 11,593,521 ops/sec ±0.83% (192 runs sampled)
long string without double quotes........................ x 16,262 ops/sec ±0.15% (195 runs sampled)
unsafe long string without double quotes................. x 808,251,968 ops/sec ±0.26% (194 runs sampled)
long string.............................................. x 16,004 ops/sec ±0.13% (194 runs sampled)
unsafe long string....................................... x 810,901,758 ops/sec ±0.24% (194 runs sampled)
number................................................... x 813,227,086 ops/sec ±0.16% (189 runs sampled)
integer.................................................. x 208,602,841 ops/sec ±0.13% (195 runs sampled)
formatted date-time...................................... x 1,412,455 ops/sec ±0.70% (192 runs sampled)
formatted date........................................... x 1,063,282 ops/sec ±0.15% (193 runs sampled)
formatted time........................................... x 1,060,232 ops/sec ±0.60% (194 runs sampled)
short array of numbers................................... x 77,987 ops/sec ±0.19% (194 runs sampled)
short array of integers.................................. x 64,438 ops/sec ±0.18% (194 runs sampled)
short array of short strings............................. x 11,024 ops/sec ±0.20% (195 runs sampled)
short array of long strings.............................. x 11,061 ops/sec ±0.16% (194 runs sampled)
short array of objects with properties of different types x 6,862 ops/sec ±0.17% (194 runs sampled)
object with number property.............................. x 809,881,883 ops/sec ±0.10% (193 runs sampled)
object with integer property............................. x 207,814,688 ops/sec ±0.15% (195 runs sampled)
object with short string property........................ x 12,129,248 ops/sec ±0.20% (194 runs sampled)
object with long string property......................... x 15,989 ops/sec ±0.16% (195 runs sampled)
object with properties of different types................ x 1,407,092 ops/sec ±0.19% (194 runs sampled)
simple object............................................ x 5,209,219 ops/sec ±0.27% (195 runs sampled)
simple object with required fields....................... x 5,354,476 ops/sec ±0.16% (194 runs sampled)
object with const string property........................ x 814,753,997 ops/sec ±0.08% (188 runs sampled)
object with const number property........................ x 812,281,777 ops/sec ±0.19% (194 runs sampled)
object with const bool property.......................... x 815,316,574 ops/sec ±0.15% (181 runs sampled)
object with const object property........................ x 814,527,351 ops/sec ±0.09% (192 runs sampled)
object with const null property.......................... x 815,133,730 ops/sec ±0.12% (194 runs sampled)
```

master

```
short string............................................. x 21,728,499 ops/sec ±0.87% (193 runs sampled)
unsafe short string...................................... x 815,436,755 ops/sec ±0.11% (184 runs sampled)
short string with double quote........................... x 13,268,536 ops/sec ±0.63% (193 runs sampled)
long string without double quotes........................ x 16,203 ops/sec ±0.32% (195 runs sampled)
unsafe long string without double quotes................. x 816,105,659 ops/sec ±0.09% (188 runs sampled)
long string.............................................. x 16,032 ops/sec ±0.16% (194 runs sampled)
unsafe long string....................................... x 814,770,840 ops/sec ±0.21% (183 runs sampled)
number................................................... x 816,578,188 ops/sec ±0.08% (181 runs sampled)
integer.................................................. x 208,419,109 ops/sec ±0.16% (193 runs sampled)
formatted date-time...................................... x 1,416,343 ops/sec ±0.25% (195 runs sampled)
formatted date........................................... x 1,030,506 ops/sec ±0.88% (192 runs sampled)
formatted time........................................... x 1,039,128 ops/sec ±0.75% (191 runs sampled)
short array of numbers................................... x 78,479 ops/sec ±0.16% (194 runs sampled)
short array of integers.................................. x 63,797 ops/sec ±0.62% (194 runs sampled)
short array of short strings............................. x 19,181 ops/sec ±0.50% (192 runs sampled)
short array of long strings.............................. x 19,258 ops/sec ±0.43% (193 runs sampled)
short array of objects with properties of different types x 9,395 ops/sec ±1.04% (188 runs sampled)
object with number property.............................. x 813,748,830 ops/sec ±0.12% (180 runs sampled)
object with integer property............................. x 208,023,114 ops/sec ±0.15% (194 runs sampled)
object with short string property........................ x 21,680,186 ops/sec ±1.17% (194 runs sampled)
object with long string property......................... x 15,958 ops/sec ±0.29% (193 runs sampled)
object with properties of different types................ x 2,018,270 ops/sec ±0.77% (191 runs sampled)
simple object............................................ x 9,878,794 ops/sec ±0.65% (192 runs sampled)
simple object with required fields....................... x 10,050,716 ops/sec ±0.73% (193 runs sampled)
object with const string property........................ x 817,234,834 ops/sec ±0.10% (180 runs sampled)
object with const number property........................ x 810,666,824 ops/sec ±0.29% (195 runs sampled)
object with const bool property.......................... x 810,548,546 ops/sec ±0.27% (191 runs sampled)
object with const object property........................ x 814,996,978 ops/sec ±0.17% (186 runs sampled)
object with const null property.......................... x 813,462,610 ops/sec ±0.20% (193 runs sampled)
```

Not only the short string benchmark degrades, but also the one for simple objects.

our benchmark stress the library in its entirety, and while this analysis hold true in isolation, the speed profile change completely when inlining is taken into consideration.

**Comment by mcollina** [comment]
> V8 has optimized version of string escaping [EscapeJSONStringImpl](https://chromium.googlesource.com/chromium/src/base/+/master/json/string_escape.cc#83) and [EscapeSpecialCodePoint](https://chromium.googlesource.com/chromium/src/base/+/master/json/string_escape.cc#37).
A javascript implementation will never beat these in C++

The problem is that you need to reach C++ to execute those, and that barrier is not cheap.

**Comment by cesco69** [comment]
mhh ok.. thanks!

**Pull request closed without merging**
