### PR TITLE
fix: generated function names collision

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

There is possible to have a function names collision. I suggest not overcomplicating things and using only generated function names.

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
The reason we use real names for functions is to ease debugging. Maybe just add an integer at the end of name?

**Comment by ivan-tymoshenko** [comment]
It will not solve the problem. I can create a field with the same name as another field name + counter.

**Comment by ivan-tymoshenko** [comment]
I don't know if it's really useful. If you mean useful in the development process, it's pretty clear what this is a function, because you see inlined arguments. If you talking about an error call stack, I would say we should always throw an explainable error and never use a runtime generated call stack to find the reason for the error.

But maybe I don't see some useful cases.

**Comment by mcollina** [comment]
I developed this module by printing out the generated source code, identify which function was causing a problem, and then change the generator. Anonymous functions would prevent this use case, or make it significantly harder.

You can achieve the same by adding a comment in the function itself.

**Comment by ivan-tymoshenko** [comment]
@mcollina What do you think about comment object properties and their types?
```js
    // {"b":{"type":"string"},"t":{"type":"object"}}
    function anonymous2 (input) {}
```

**Comment by mcollina** [comment]
What I need is the "property chain" that lead to that function., what in the original code was `name + key + subkey`. This always indicated the path to a given object.

**Comment by ivan-tymoshenko** [comment]
I will think how to do it clearly. I don't want to pass additional function argument through bunch of core functions to use it in comments in the generated code.

**Comment by ivan-tymoshenko** [comment]
@mcollina I rewrote it. It adds a comment with function name. You can merge it, but I still think that it's overcomplicate the code.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
