### PR TITLE
fix: merged schemas caching

### LINKED ISSUE #676: merged schema cache is messed up
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x

### Plugin version

5.11.0

### Node.js version

20.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I suspect it is deal to the merged schema cache is not properly handled, which means two seperate build procedure may try to use the same cache but it never exists.

### Steps to Reproduce

```js
import { build } from 'fast-json-stringify'

const schema = {
  type: 'object',
  properties: {
    enums: {
      type: 'string',
      anyOf: [
        { type: 'string', const: 'FOO' },
        { type: 'string', const: 'BAR' },
        { type: 'string', const: 'BAZ' },
      ]
    }
  }
}

build(schema, {
  schema: {}
})

build(schema, {
  schema: {}
})
```

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
Fix #676

### CODE REVIEW

**Comment by mcollina** [comment]
Does is include also the the other commit that was reverted?

**Comment by ivan-tymoshenko** [comment]
Yeap, I reverted reverted commits (first two one in this PR). So it's double reverted commits. Not sure if it's the cleanest way to do that.

**Comment by mcollina** [comment]
Does this pass Fastify test suite?

**Comment by ivan-tymoshenko** [comment]
yes

**Review by climba03003 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
