### PR TITLE
refactor: remove duplicate ref resolving in object serializer builder

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
You write it is removing the duplicate. Where is the first occurence? Just that I can understand it better for the approval.

**Comment by ivan-tymoshenko** [comment]
> You write it is removing the duplicate. Where is the first occurence? Just that I can understand it better for the approval.

https://github.com/fastify/fast-json-stringify/blob/4a4251a2a37523bedc5a4962612534f8e03f9f90/index.js#L849

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ivan-tymoshenko** [comment]
@mcollina Can we merge this?

**Comment by Eomm** [comment]
Is it possible to update the coverage values too?

**Comment by ivan-tymoshenko** [comment]
> Is it possible to update the coverage values too?

No, `serializer.js` has the lowest branch coverage number. I will take care about test coverage for all files later.

**Pull request merged**
