### PR TITLE
chore: add linting check to npm test command

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**

### CODE REVIEW

**Review by Uzlopak — CHANGES_REQUESTED** [review]
We removed linting from tests on purpose. What actually has to be done is adding

```
"pre-commit": [
  "lint",
  "test"
]
```

to package.json so that pre-commit runs linting before checking in.

**Comment by Uzlopak** [comment]
@Fdawgs

**Comment by ivan-tymoshenko** [comment]
IMHO it's just inconvenient. When I have written some code and want to check that everything is fine, I will have to run two commands instead of one.

**Comment by Uzlopak** [comment]
I get your point.  but lets discuss this with Fdawgs.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Uzlopak — APPROVED** [review]

**Pull request merged**
