### PR TITLE
Revert "perf: use `node:` prefix to bypass require.cache call for builtins (#644)"

### PR DESCRIPTION
**Pull request by mcollina**
This reverts commit 4073e5b6c9b2f4c6b4a3cea1f0f1d6f0ba89e769.

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Fixes https://github.com/fastify/fast-json-stringify/issues/659

### CODE REVIEW

**Comment by Uzlopak** [comment]
IMO 
Why do we not reach out also to next.js and report this? Maybe they need to fix resolving node packages? I mean, there is probably other cases which are independent from us, which break also.

**Comment by mcollina** [comment]
Agreed. I guess it's simpler to revert for now and reassess for them.
I think we could avoid them for libraries and keep them in Fastify proper.

**Comment by inlet** [comment]
Thanks @mcollina for addressing this issue so quickly! Looking forward to a new working release 🙏

**Review by Fdawgs — APPROVED** [review]

**Comment by Fdawgs** [comment]
Bloody front end developers ruining everything. 😂

**Comment by inlet** [comment]
@Fdawgs haha! Sorry mate

**Comment by Uzlopak** [comment]
Who is gonna report it to next.js?

Maybe @inlet?

**Comment by inlet** [comment]
@Uzlopak: https://github.com/vercel/next.js/issues/28774

**Pull request merged**
