### PR TITLE
serializer.js - asNumber

### PR DESCRIPTION
**Pull request by yaki3355**
#474

### CODE REVIEW

**Review by ivan-tymoshenko — APPROVED** [review]
LDTM

**Comment by ivan-tymoshenko** [comment]
@yaki3355 Can you add a test?

**Comment by yaki3355** [comment]
> @yaki3355 Can you add a test?

Hey @ivan-tymoshenko 
working on it

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by yaki3355** [comment]
> > @yaki3355 Can you add a test?
> 
> Hey @ivan-tymoshenko working on it

After pushing Infinity.test.js to repo
I got this message:
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Should I fork from fastify again and then add Infinity.test.js?

**Comment by samchon** [comment]
> > @yaki3355 It would better to add the `!Number.isFinite()` condition on the `asInteger()`.
> 
> @samchon can you explain why? In terms of typeof Infinity/-Infinity is number.

Infinite is out of the integer range, but JS does not distinguish integer and float

**Comment by samchon** [comment]
Your insight seems right. If user defined json schema as inter but infite value comes, its responsibility of that user.

**Comment by yaki3355** [comment]
And if json schema as number and Infinity value comes?

**Comment by mcollina** [comment]
This landed. Please open a new issue if there is a bug.

**Comment by yaki3355** [comment]
#477

**Pull request merged**
