### PR TITLE
Fix allOf with $ref property

### PR DESCRIPTION
**Pull request by mcollina**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]
lgtm

**Review by ivan-tymoshenko — APPROVED** [review]
lgtm

**Comment by Eomm** [comment]
The comment message is wrong

image

**Comment by mcollina** [comment]
yep, I've already released, and folks freaks out if the commit message is altered.

**Pull request merged**
