### PR TITLE
Removed fast-safe-stringify, use plain JSON.stringify.

### PR DESCRIPTION
**Pull request by mcollina**
As titled. We removed it from fastify long ago anyway.

### CODE REVIEW

**Comment by SimenB** [comment]
That means there's no way to handle circular objects :( Thoughts on that? I can just use an old version, that makes me a bit sad, though

**Comment by mcollina** [comment]
@SimenB you should specify a schema, or just use `fast-safe-stringify`  yourself and then send the JSON down.

**Comment by SimenB** [comment]
Right now we have an `extras` field on the object (we use this for a logger) which can be whatever, everything else logged is a schema.

Passing just that part through `fast-safe-stringify` manually should work though. Would I have to send the result from that through `JSON.parse` before passing it to this module to avoid double-escaping?

**Comment by mcollina** [comment]
You can possibly just add a `toJSON` function on that object.

**Pull request merged**
