### PR TITLE
perf: add schemas to the validator only if they are needed

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Does this improve cold start? By how much?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ivan-tymoshenko** [comment]
@adrai Do you have your test env for testing cold start with a lot of JSON schemas?

**Comment by adrai** [comment]
based on: https://github.com/adrai/fastify-slower-schema-resolving
fastify/fast-json-stringify (v5.1.0): approx. 690ms
fastify/fast-json-stringify (master [v5.3.0]): approx. 235ms
fastify/fast-json-stringify (add-schemas-to-validator-only-if-validator-is-used): approx. 166ms

**Comment by mcollina** [comment]
wow!!!

**Comment by adrai** [comment]
timid question: is there something that prevents this to be released? maybe waiting for #546 ?

**Comment by ivan-tymoshenko** [comment]
> timid question: is there something that prevents this to be released? maybe waiting for #546 ?

Yes, you are right. I will close #546 this week.

**Pull request merged**
