### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by cemremengu**
Add more tests for #134

### CODE REVIEW

**Comment by cemremengu** [comment]
@mcollina The schema below still converts `null` to `0` should we change that?

```js
  const schema = {
    title: 'simple object with multi-type nullable primitive',
    type: 'object',
    properties: {
      data: {
        type: 'integer' // works if ['integer']
      }
    }
  }
```

**Comment by mcollina** [comment]
How does it behave with an explicit undefined? What would you propose?

**Comment by cemremengu** [comment]
For `undefined` it will just return `{}`. 

I propose to not convert `null` to `0` since they are not the same thing especially in database terms. So `'integer'` and `['integer']` should produce the same output. However, then, having `['integer', null]` will only for verbosity instead of providing new functionality.

I am a bit confused actually 😄 In essence I don't want it to have runtime errors for not specifying `null` explicitly but also want to have the field as `null` there instead of `0` or completely omitting it.

**Comment by mcollina** [comment]
Go with your best shot, we’ll change it if we need to.

Il giorno dom 3 mar 2019 alle 21:54 Cemre Mengu <notifications@github.com>
ha scritto:

**Comment by StarpTech** [comment]
@cemremengu don't forget the [JSON-Schema testuite](https://github.com/fastify/fast-json-stringify/tree/master/test/json-schema-test-suite) if you want to improve the tests. It would be great to have a structure.

**Pull request merged**
