### PR TITLE
perf: replace joins with fast-array-join

### PR DESCRIPTION
**Pull request by anonrig**

### CODE REVIEW

**Comment by Uzlopak** [comment]
I dont like to fragment our code with more npm dependencies. We should focus on improving the perf in the runtime. For me unfortunately a -1.

**Comment by anonrig** [comment]
@Uzlopak Would you change your decision if we move this to fastify organization?

**Comment by mcollina** [comment]
Does this improve things at all?

**Comment by Uzlopak** [comment]
I looked the changes and the places are in generating the serializer-functions. So the performence improvements should be at startup but not at runtime.

**Comment by anonrig** [comment]
> Does this improve things at all?

The benchmarks did not show any improvements and were highly inconsistent across different runs.

**Comment by Eomm** [comment]
I think the improvement is proportional to how many response schema the user is processing.

I recall a benchmark about it, i must searched it

**Review by climba03003 — COMMENTED** [review]
Cold start is not really a consideration.
I would say that it is good to have but not a must.

**Comment by mcollina** [comment]
I don't think we should pull in another dep without a clear performance improvement.

Thanks @anonrig anyway!

**Comment by jsumners** [comment]
> I don't think we should pull in another dep without a clear performance improvement.
> 
> Thanks @anonrig anyway!

Agreed. Even if there were an improvement, I think the module's code is small enough to inline.

**Pull request closed without merging**
