### PR TITLE
chore: unnecessary stringify calls

### PR DESCRIPTION
**Pull request by Eomm**
Not sure about the `randomUUID()` performance.
I would use something more basic as `Math.random()` or `crypto.randomBytes`.

Need to try it

### CODE REVIEW

**Review by zekth — APPROVED** [review]
LGTM

`Math.random` can have collision AFAIK

**Review by RafaelGSS — COMMENTED** [review]
Could you share the benchmark?

**Comment by Eomm** [comment]
Running the script on Node.js 16

```
randomInt x 121,083,649 ops/sec ±0.35% (595 runs sampled)
randomInt + now x 9,471,249 ops/sec ±0.07% (596 runs sampled)
uuid x 24,935,836 ops/sec ±0.74% (589 runs sampled)
math.random x 113,739,051 ops/sec ±1.56% (566 runs sampled)
math.random + now x 6,165,940 ops/sec ±0.44% (591 runs sampled)
```

> Math.random can have collision AFAIK

True, but I'm not so lucky and I never hit this case.
For this, I tried the `+ now()` concatenation but it is the worse performance.

```js
const Benchmark = require('benchmark')
Benchmark.options.minSamples = 500

const crypto = require('crypto')

Benchmark.Suite()
  .add('randomInt', function () { crypto.randomInt(10e6) })
  .add('randomInt + now', function () { return `${Date.now()}${crypto.randomInt(10e6)}` })
  .add('uuid', function () { crypto.randomUUID() })
  .add('math.random', function () { return Math.random() * 10e6 })
  .add('math.random + now', function () { return `${Date.now()}${Math.random() * 10e6}` })
  .on('cycle', function (event) { console.log(String(event.target)) })
  .on('complete', function () {})
  .run()
```

**Comment by RafaelGSS** [comment]
> Running the script on Node.js 16
> 
> ```
> randomInt x 121,083,649 ops/sec ±0.35% (595 runs sampled)
> randomInt + now x 9,471,249 ops/sec ±0.07% (596 runs sampled)
> uuid x 24,935,836 ops/sec ±0.74% (589 runs sampled)
> math.random x 113,739,051 ops/sec ±1.56% (566 runs sampled)
> math.random + now x 6,165,940 ops/sec ±0.44% (591 runs sampled)
> ```

This benchmark in comparison to the master has degraded the performance? I mean, I could not compare with the result in the README or my local benchmarks.

**Comment by mcollina** [comment]
IMHO randomUUID() is fast enough to not cause problems in practice.

**Pull request merged**
