### PR TITLE
fix: escape single quote when building error message for required property

### PR DESCRIPTION
**Pull request by tomastauer**
closes https://github.com/fastify/fast-json-stringify/issues/715

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by tomastauer** [comment]
@ivan-tymoshenko could you please try to restart the CI? Seems the fail is not related to the changes in this PR

**Comment by gurgunday** [comment]
Seems like there is an issue on node 14?

This is the 4th run

**Comment by Uzlopak** [comment]
Lets ignore it.

**Review by gurgunday — COMMENTED** [review]
Just to make sure, can you please add another test for double quote as well:

```js
const stringify = build({
    type: 'object',
    properties: {
      '"': { type: 'string' }
    },
    required: [
      '"'
    ]
  })
```

**Review by gurgunday — APPROVED** [review]
yeah lgtm, that regex seems necessary

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
