### PR TITLE
refactor: remove const validation branch

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
My bad, I've badly rebased #504 on #511. It doesn't fail because it is an unreachable code now.

### CODE REVIEW

**Comment by Uzlopak** [comment]
Is the const stuff now basically reverted?

**Comment by ivan-tymoshenko** [comment]
> Is the const stuff now basically reverted?

Not completely. It works properly. The code I accidentally added is unreachable because the proper check exists.
https://github.com/fastify/fast-json-stringify/blob/8997bf19ae0377d5ab96615b3e4c6e858f2c3739/index.js#L778

Here the code was removed:
https://github.com/fastify/fast-json-stringify/pull/511/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L868

Here it was accidentally added:
https://github.com/fastify/fast-json-stringify/pull/504/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R849

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
can you resolve the conflicts?

**Pull request merged**
