### PR TITLE
chore: add nullable for $ref

### PR DESCRIPTION
**Pull request by xtx1130**
ref: https://github.com/fastify/fast-json-stringify/issues/406

ps: I'm not sure if these test cases is enough for this pr.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
It is not the real fix to the issue. The fix should be the property of resolved `$ref` can be overrided. It should not limited to nullable only.

**Comment by xtx1130** [comment]
Why need to support all the properties? I think this is just a json pointer string and `nullable` just represent `$ref`(JSON pointer) can be `null`. for [rfc6901](https://datatracker.ietf.org/doc/html/rfc6901):
> Note that JSON pointers can contain the NUL (Unicode U+0000)
   character.

I'm not sure if I understand this correctly

**Comment by climba03003** [comment]
> Why need to support all the properties? I think this is just a json pointer string and `nullable` just represent `$ref`(JSON pointer) can be `null`. for [rfc6901](https://datatracker.ietf.org/doc/html/rfc6901):
> 
> > Note that JSON pointers can contain the NUL (Unicode U+0000)
> > character.
> 
> I'm not sure if I understand this correctly

Because it is how the spec tells.

From [`JSON Schema 4-7`](https://json-schema.org/understanding-json-schema/structuring.html#ref), 
> When an object contains a $ref property, the object is considered a reference, not a schema. Therefore, **any other properties** you put in that object will not be treated as JSON Schema keywords and will be **ignored by the validator**.

From [`JSON Schema 2019-09`](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.7.7.1.1)
> Applications MAY make decisions on which of multiple annotation values to use based on the schema location that contributed the value. This is intended to allow flexible usage.

The question is, `support` all keywords to be overrided or `do not support`. For easy usage, I would support all.

**Comment by xtx1130** [comment]
thanks for you detailed explanation. And I find the [JSON Reference document](https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03), in Syntax chapter:
> The "$ref" string value contains a URI [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)], which identifies
   the location of the JSON value being referenced.  It is an error
   condition if the string value does not conform to URI syntax rules.
   Any members other than "$ref" in a JSON Reference object SHALL be
   ignored.

So, I think it should not be fixed at all.

**Comment by mcollina** [comment]
I don't think a fix is needed.

**Comment by climba03003** [comment]
I would close this PR and the issue together.
If anyone would like the support of `JSON Schema 2019-09` flexible usage mentioned in https://github.com/fastify/fast-json-stringify/pull/408#issuecomment-1106078468
It deserves a new issue for the discussion first.

**Pull request closed without merging**
