### PR TITLE
remove luxon

### PR DESCRIPTION
**Pull request by Uzlopak**
We dont need luxon when we can replace them with three liners...

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
I would much rather rely on luxon to deal with all of the non-trivial date calculations than attempt to do it ourselves. At least until Temporal is widely available. 

👎

**Comment by Uzlopak** [comment]
I set the date to a fixed timestamp. So there is actually no transformation needed anymore ;)

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]
Simpler to read IMHO

**Pull request merged**
