### PR TITLE
Drop support for long as we have BigInt.

### LINKED ISSUE #314: optional dependency long should actually be required
## 🐛 Bug Report

I am using fastify in a repo with yarn v2 (berry) and using the zero-install feature which is stricter with dependency management. 

During compilation i get the following error:
```
(node:1536) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
 > pnp:C:\Users\ArunG\Repos\GH\gazo\.yarn\cache\fast-json-stringify-npm-2.5.3-5f61461930-b6d1204da2.zip\node_modules\fast-json-stringify\index.js:15:19: error: [@yarnpkg/esbuild-plugin-pnp] fast-json-stringify tried to access long, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: long (via "long")
Required by: fast-json-stringify@npm:2.5.3 (via C:\Users\ArunG\Repos\GH\gazo\.yarn\cache\fast-json-stringify-npm-2.5.3-5f61461930-b6d1204da2.zip\node_modules\fast-json-stringify\index.js)

    15 │   isLong = require('long').isLong
```

Saw `fast-json-stringify` was a sub dep of `fastify`
image

I see you guys try to handle this with the try catch block but i think itd be easier if you guys had a direct dependency on the `long` package
image
image

I was able to get around this issue using a feature in berry to correct dependencies, [see](https://yarnpkg.com/configuration/yarnrc#packageExtensions), but thought of raising this issue as more and more users will start using pnp.

## To Reproduce

If you need a sample to reproduce this, let me know.

## Proposal

Move ` long` from being a devDep to a direct dep.

## Your Environment

- *node version*: 12.16.2
- *fastify version*: ^3.12.0
- *os*: Windows,
- *yarn*: 2.4.1

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #314.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
cc @gajus

**Review by jsumners — APPROVED** [review]
LGTM

**Review by L2jLiga — APPROVED** [review]
LGTM

**Comment by duzenko** [comment]
Which version has this been released with? I'm on 2.7.3 and still get this loader exception

**Comment by Eomm** [comment]
It is not released yet. it is on the next branch

Here there should be a workaround till the next major
https://github.com/fastify/fast-json-stringify/issues/314

**Pull request merged**
