### PR TITLE
Corrects integer handling

### LINKED ISSUE #133: multiple types with null fails
Related to #77
Tested on master this morning.

Please find below the test code:
```js
'use strict';

const fastJsonStringify = require('fast-json-stringify');

const f = fastJsonStringify({
  type: 'object',
  properties: {
    data: {
      type: ['integer', 'null']
    }
  }
});

console.log(f({data:4}))
```

The expected output is `{"data":4}` but I've got `{"data":null}`.

### PR DESCRIPTION
**Pull request by bhamon**
Closes #133

### CODE REVIEW

**Comment by bhamon** [comment]
The hidden question was: is fast-json-stringify expected to be JSON-schema compliant ?
If yes, this call should throws.
If no, I can ignore the last check I introduced in the test suite and go on with the PR.

**Comment by mcollina** [comment]
I think we should throw if it’s a required field, or omit it if it’s not.

@delvedor?

**Comment by bhamon** [comment]
By "required" are you talking about the parent object?
Because if I have the following schema it is still invalid to coerce the `data=null` value to `0`:
```
{
  type: 'object',
  properties: {
    data: {
      type: 'integer'
    }
  }
}
```

**Comment by mcollina** [comment]
If `data = null`  is passed, nothing should be produced, and it should throw if that property is required.

**Comment by mcollina** [comment]
What's the status of this @bhamon?

**Comment by bhamon** [comment]
I'm currently overcharged on other subjects. I'll get back to this as soon as I have some free time.

**Comment by cemremengu** [comment]
Ping @bhamon

**Comment by cemremengu** [comment]
@mcollina @delvedor is it possible to merge this and I will add the required test case in separate PR ?

**Comment by delvedor** [comment]
@cemremengu are you able to push directly to this pr?
Otherwise, you can open a new one and maintain the same commits that are in this one.

**Comment by cemremengu** [comment]
May I patch release this?

**Comment by bhamon** [comment]
The added test (https://github.com/fastify/fast-json-stringify/pull/134/commits/3380dc16f9eb9803cc0326865a59c999aa039790#diff-bfdcad0d83d6ed08c8e0c1ad2d02ddf8R31) doesn't check that `{"data": null}` works, 50% coverage.
Also, the PR doesn't solve the illegitimate `{"data": null}` serialization problem.

**Comment by cemremengu** [comment]
@bhamon would you like send another PR or at least provide failing cases so someone else can patch it?

**Comment by cemremengu** [comment]
Ah I guess you mean this comment ?https://github.com/fastify/fast-json-stringify/pull/134#issuecomment-454698980

**Pull request merged**
